import pymunk
import pyglet
from sim_utils import get_vertices_from_img
import numpy as np

class Receptor:
    """Class representing a generic receptor. Many subtypes of receptors are possible."""
    
    receptors = ["A", "B"]

    receptor_imgs = {
        "A" : "images/receptor_a.png",
        "B" : "images/receptor_b.png"
    }

    def __init__(
        self,
        space,
        env_objects,
        object_batch,
        receptor
    ):
        self.space = space
        self.env_objects = env_objects
        self.object_batch = object_batch
        if receptor not in self.receptors:
            raise Exception(f"Must choose from following receptors to initialize: {self.receptors}.")
        self.receptor = receptor
        self.image = pyglet.resource.image(self.receptor_imgs[receptor])
        self.image.anchor_x = self.image.width // 2
        self.image.anchor_y = self.image.height // 2

    def spawn(self, x: float, y: float, angle: int = 0, mass: int = 1) -> pymunk.Body:
        """Spawns a nucleus."""
        vertices = get_vertices_from_img(self.receptor_imgs[self.receptor], 1)
        
        moment = pymunk.moment_for_poly(mass, vertices)
        new_body = pymunk.Body(mass, moment)
        new_body.position = x, y
        new_body.angular_velocity_limit = 5.0
        new_body.velocity_limit = 200
        new_body.angle = angle
        poly = pymunk.Poly(new_body, vertices)
        receptor = pyglet.sprite.Sprite(img=self.image, x=x, y=y, batch=self.object_batch)
        receptor.anchor_x = self.image.width // 2
        receptor.anchor_y = self.image.height // 2
        
        new_body.visual_shape = receptor
        self.env_objects.append(new_body)
        self.space.add(new_body, poly)
        self.body = new_body
        return new_body
    
    def calc_ligand_forces(self, ligands: dict[str, list[pymunk.Body]], kd: float) -> None:
        """Calculates forces generated by ligands in the environment being in proximity
        to the receptor."""

        if not ligands[self.receptor]: return

        tip_local = (0, 30) # Defines the tip of the receptor to use instead of the Body's center
        tip_world = self.body.local_to_world(tip_local) 
        receptor_pos = np.array(tip_world) # Modify area that's used 
        pos = np.array([l.position for l in ligands[self.receptor]])

        # Calculate distance between ligands and receptor
        diff = pos - receptor_pos
        dist_sq = np.sum(diff**2, axis=1)
        dist = np.sqrt(dist_sq)

        max_dist = 200
        strength = (1 / kd) / 4
        mask = (dist < max_dist) # or scale by 1/distance so it slows down?(dist > 25)
        force_mag = np.where(mask, strength / (dist_sq + 100), 0.0)

        inv_dist = np.where(mask, 1.0 / dist, 0.0)
        total_forces = -diff * (force_mag * inv_dist)[:, np.newaxis]

        # Apply forces
        for i, body in enumerate(ligands[self.receptor]):
            body.apply_force_at_world_point(tuple(total_forces[i]), body.position)

    def get_center(self) -> tuple[float, float]:
        """Gets the center of the object."""
        return self.body.position.x, self.body.position.y
